// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgPp_KTAodKOKS7XQl3DtaAdDaigoWjUs',
    appId: '1:37845653677:web:1679658d9a92e9b3a10e24',
    messagingSenderId: '37845653677',
    projectId: 'animalswale-50d5b',
    authDomain: 'animalswale-50d5b.firebaseapp.com',
    storageBucket: 'animalswale-50d5b.appspot.com',
    measurementId: 'G-LRZNSQZKRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABIpOVt3IVIN0dZN4pVjmHiFuTzOLtJRk',
    appId: '1:37845653677:android:2e77ed3e719c99a2a10e24',
    messagingSenderId: '37845653677',
    projectId: 'animalswale-50d5b',
    storageBucket: 'animalswale-50d5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAiUJlmcuWe8rjkO8PUmVLqy6ZepQSplc',
    appId: '1:37845653677:ios:62a78f418b505bf9a10e24',
    messagingSenderId: '37845653677',
    projectId: 'animalswale-50d5b',
    storageBucket: 'animalswale-50d5b.appspot.com',
    iosBundleId: 'animal.com.animal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAiUJlmcuWe8rjkO8PUmVLqy6ZepQSplc',
    appId: '1:37845653677:ios:e01ba7ef529013d7a10e24',
    messagingSenderId: '37845653677',
    projectId: 'animalswale-50d5b',
    storageBucket: 'animalswale-50d5b.appspot.com',
    iosBundleId: 'animal.com.animal.RunnerTests',
  );
}
